export type Lang = "en" | "es";

export const en = {
  nav: [
    { href: "/sitios-web", label: "Websites" },
    { href: "/mvp-webapp", label: "Webapp MVPs" },
  ],
  brand: "Catalina Cobap",
  links: {
    email: "mailto:catalinacobap@gmail.com",
    linkedin: "#",
    github: "#",
    cv: "https://docs.google.com/document/d/1ZT_LXHi_dx4Z-HlCwThasDIjoyxdMLnrpJmPymGnG54/edit?usp=sharing",
  },
  hero: {
    label: "Web design + development / Costa Rica",
    preHeadline: "Not every web project needs the same thing.",
    headline: "WEBSITES AND MVPs, BUILT FOR WHAT THEY NEED TO DO.",
    body: "Design and development from scratch — from a new web presence to the first functional version of a product.",
    cta: "Start a project",
    secondaryCta: "See what I build",
    strip: "WEBSITES · WEBAPP MVPs · DESIGN + DEVELOPMENT · / COSTA RICA",
  },
  positioning: {
    num: "Positioning",
    title: "First, what it needs to do. Then, how to build it.",
    body: "Every project starts by understanding what it needs to communicate, enable, or solve. Structure, design, and technology come after that.",
  },
  glance: {
    num: "At a glance",
    items: [
      ["Focus", "Websites + webapp MVPs"],
      ["Websites", "$1,000–$1,500 USD"],
      ["Webapp MVPs", "From $2,000 USD"],
      ["Based in", "Costa Rica"],
      ["Languages", "Spanish + English"],
    ],
  },
  about: {
    num: "About",
    quote: "“I design and develop every project from scratch — around what it needs to do, not around a solution decided in advance.”",
    attribution: "— Catalina",
    role: "Web designer + developer, Costa Rica.",
  },
  build: {
    num: "What I build",
    title: "Two starting points.",
    intro: "One needs to communicate. The other needs people to be able to do something.",
    services: [
      {
        label: "Websites",
        headline: "“I need a web presence.”",
        body: "For businesses and independent professionals that need a new website — whether it is their first serious site or a new one built to completely replace the one they have today.",
        price: "$1,000–$1,500 USD",
        cta: "View Websites",
        link: "/sitios-web",
      },
      {
        label: "Webapp MVP",
        headline: "“I need people to be able to do something inside the product.”",
        body: "For ideas that need to become a functional first version with users, data, flows, dashboards, integrations, or custom logic.",
        price: "From $2,000 USD",
        cta: "View Webapp MVPs",
        link: "/mvp-webapp",
      },
    ],
  },
  process: {
    num: "Process",
    title: "One continuous thread, from the first conversation to launch.",
    steps: [
      { title: "Define", text: "What it needs to do, who needs it, and what actually matters." },
      { title: "Shape", text: "Structure, hierarchy, flows, and visual direction." },
      { title: "Build", text: "Design and development together, using the technology that makes sense for the project." },
      { title: "Launch", text: "Testing, production setup, domain, and going live." },
    ],
  },
  work: {
    num: "Selected work",
    title: "Different projects. Different solutions.",
    intro: "Each project takes shape around what it needs to communicate, organize, or enable.",
    projects: [
      {
        n: "01",
        cat: "Medtech + AI",
        name: "Aster Intel",
        desc: "An AI-powered intelligence platform, made clear for investors.",
        link: "Visit website",
        url: "https://asterintel.ai",
      },
      {
        n: "02",
        cat: "Custom home building",
        name: "Kai Custom Homes",
        desc: "A premium custom home builder with a presence to match.",
        link: "Visit website",
        url: "https://kai-customhomes.com",
      },
      {
        n: "03",
        cat: "Web services",
        name: "Baileyscode",
        desc: "A Costa Rican web studio for tourism and hospitality.",
        link: "Visit website",
        url: "https://www.baileyscode.com",
      },
      {
        n: "04",
        cat: "Tourism",
        name: "Costa Rica Descents",
        desc: "A large tour catalog, organized for easy discovery.",
        link: "Visit website",
        url: "https://costaricadescents.com",
      },
      {
        n: "05",
        cat: "Hospitality",
        name: "Ester’s Place",
        desc: "A bilingual guesthouse with a complete online presence.",
        link: "Visit website",
        url: "https://estersplace.com",
      },
    ],
  },
  fit: {
    num: "A good fit",
    title: "It works best when you want to build something properly.",
    items: [
      { title: "You need something built for your case", text: "Not a generic solution forced to fit, but something designed around the project." },
      { title: "You want to start with a clean foundation", text: "A new project, or a new version, without carrying decisions that no longer make sense." },
      { title: "You understand the problem", text: "You know what needs to improve, launch, or start working, even if you do not yet know exactly how it should be built." },
      { title: "You want design + development together", text: "One person thinks through the experience, designs it, and builds it from beginning to end." },
    ],
  },
  investment: {
    num: "Investment",
    title: "Clear scope. Clear price.",
    services: [
      {
        title: "Websites",
        price: "$1,000–$1,500 USD",
        body: "For new websites and completely new websites built to replace an existing one.",
        cta: "View Websites",
        link: "/sitios-web",
      },
      {
        title: "Webapp MVPs",
        price: "From $2,000 USD",
        body: "For first functional versions of web products.",
        cta: "View MVPs",
        link: "/mvp-webapp",
      },
    ],
    footnote: "After I understand the project, I define the scope and price before work begins.",
  },
  contact: {
    num: "Contact",
    title: "Have something you need to build?",
    body: "Tell me what you want to launch, replace, or put into operation.",
    cta: "Start a project",
    bestWay: "Best way to start",
    online: "Find me online",
    linkedin: "LinkedIn",
    github: "GitHub",
  },
  footer: {
    backToTop: "Back to top",
    cv: "Download CV",
    tagline: "Web design + development / Costa Rica",
  },
};
export const es = {
  nav: [
    { href: "/", label: "Inicio" },
    { href: "/sitios-web", label: "Sitios Web" },
    { href: "/mvp-webapp", label: "MVPs Webapp" },
    { href: "#positioning", label: "Posicionamiento" },
    { href: "#work", label: "Lo que construyo" },
    { href: "#projects", label: "Trabajo seleccionado" },
    { href: "#contact", label: "Contacto" },
  ],
  brand: "Catalina Cobap",
  links: {
    email: "mailto:catalinacobap@gmail.com",
    linkedin: "#",
    github: "#",
    cv: "https://docs.google.com/document/d/1ZT_LXHi_dx4Z-HlCwThasDIjoyxdMLnrpJmPymGnG54/edit?usp=sharing",
  },
  hero: {
    label: "Diseño web + desarrollo / Costa Rica",
    titleA: "Su negocio ha crecido.",
    titleB: "su sitio web debería reflejarlo.",
    sub: "Sitios web nuevos y rediseños completos para negocios listos para una presencia que esté a la altura del trabajo.",
    cta: "Iniciar un proyecto",
    strip: "Sitios web nuevos + rediseños completos",
    stripSuffix: "/ Costa Rica",
  },
  positioning: {
    num: "Posicionamiento",
    title: "Cuando el trabajo mejora, el sitio web tiene que ponerse al día.",
    body: "Construido desde cero para estar a la altura del negocio que tiene hoy. Sin plantillas ni parches.",
    glanceTitle: "De un vistazo",
    glance: [
      ["Enfoque", "Sitios web nuevos + rediseños completos"],
      ["Ideal para", "Negocios + profesionales independientes"],
      ["Ubicada en", "Costa Rica"],
      ["Idiomas", "Español + Inglés"],
    ],
  },
  about: {
    num: "Sobre mí",
    statement:
      "Construyo cada sitio web desde cero — diseñado y desarrollado alrededor de lo que el proyecto realmente necesita.",
    name: "Catalina",
    monogram: "C.",
    note: "Diseñadora y desarrolladora web, Costa Rica.",
  },
  build: {
    num: "Lo que construyo",
    title: "Dos tipos de proyectos.",
    intro: "Trabajo donde la experiencia se puede repensar de verdad — no remendar.",
    new: {
      tag: "Sitio web nuevo",
      lead: "Primera presencia en línea seria.",
      body: "Construido desde cero, alrededor del negocio que tiene hoy.",
    },
    rebuild: {
      tag: "Rediseño completo",
      lead: "El sitio actual se quedó corto.",
      body: "Conservar lo que funciona, reconstruir el resto.",
    },
    processTitle: "De la dirección al lanzamiento",
    process: [
      { n: "01", t: "Definir", d: "Qué ofrece, quién lo necesita, qué cambió." },
      { n: "02", t: "Moldear", d: "Estructura, jerarquía y dirección visual." },
      { n: "03", t: "Construir", d: "Diseño y desarrollo juntos, sin plantillas." },
      { n: "04", t: "Lanzar", d: "Configuración de producción, dominio, en línea." },
    ],
  },
  work: {
    num: "Trabajo seleccionado",
    title: "Negocios diferentes. Sitios web diferentes.",
    intro: "Cada proyecto se forma alrededor de lo que el negocio necesita decir.",
    projects: [
      {
        n: "01",
        cat: "Medtech + IA",
        name: "Aster Intel",
        desc: "Una plataforma de inteligencia, clara para inversionistas.",
        link: "Visitar sitio",
        url: "https://asterintel.ai",
      },
      {
        n: "02",
        cat: "Construcción de casas a medida",
        name: "Kai Custom Homes",
        desc: "Un constructor premium con presencia a la altura.",
        link: "Visitar sitio",
        url: "https://kai-customhomes.com",
      },
      {
        n: "03",
        cat: "Servicios web",
        name: "Baileyscode",
        desc: "Un estudio web costarricense para turismo y hospitalidad.",
        link: "Visitar sitio",
        url: "https://www.baileyscode.com",
      },
      {
        n: "04",
        cat: "Turismo",
        name: "Costa Rica Descents",
        desc: "Un catálogo grande de tours, organizado para explorar.",
        link: "Visitar sitio",
        url: "https://costaricadescents.com",
      },
      {
        n: "05",
        cat: "Hospitalidad",
        name: "Ester’s Place",
        desc: "Un hospedaje bilingüe con presencia en línea completa.",
        link: "Visitar sitio",
        url: "https://estersplace.com",
      },
    ],
  },
  fit: {
    num: "Un buen encaje",
    title: "Funciona mejor cuando está listo para un cambio real.",
    items: [
      { n: "01", t: "Empieza más en serio", d: "El trabajo ya es profesional — el sitio debería decirlo." },
      { n: "02", t: "Superó el sitio actual", d: "El negocio avanzó. El sitio web, no." },
      { n: "03", t: "Quiere empezar limpio", d: "Repensar estructura y diseño de verdad, sin remiendos." },
      { n: "04", t: "Diseño + desarrollo juntos", d: "Una misma persona lo diseña y lo construye, de la idea al lanzamiento." },
    ],
  },
  contact: {
    num: "Contacto",
    title: "¿Listo para un sitio web que esté a la altura del negocio actual?",
    body: "Cuénteme qué ha cambiado y qué debería hacer mejor la nueva versión.",
    cta: "Iniciar un proyecto",
    bestWay: "Mejor forma de empezar",
    online: "Encuéntreme en línea",
    linkedin: "LinkedIn",
    github: "GitHub",
  },
  footer: {
    backToTop: "Volver arriba",
    cv: "Descargar CV",
    tagline: "Diseño web + desarrollo / Costa Rica",
  },
};
export type Copy = typeof en;

export const copy: Record<Lang, Copy> = { en, es };
