export type Lang = "en" | "es";

export const en = {
  nav: [
    { href: "#positioning", label: "Positioning" },
    { href: "#work", label: "What I build" },
    { href: "#projects", label: "Selected work" },
    { href: "#contact", label: "Contact" },
  ],
  brand: "Catalina Cob",
  links: {
    email: "mailto:catalinacobap@gmail.com",
    linkedin: "#",
    github: "#",
    cv: "#",
  },
  hero: {
    label: "Web design + development / Costa Rica",
    titleA: "Your business has grown.",
    titleB: "your website should look like it.",
    sub: "Custom websites for businesses and independent professionals ready for an online presence that reflects the quality of their work today.",
    cta: "Start a project",
    strip: "New websites + complete rebuilds",
    stripSuffix: "/ Costa Rica",
  },
  positioning: {
    num: "02 / Positioning",
    title: "When the work gets better, the website has to catch up.",
    body: [
      "Maybe you started with a template, a simple website, an Instagram page, or something you put together when the business was still taking shape.",
      "It worked for that stage.",
      "Now the work is stronger, the offer is clearer, and the business feels more established — but the website still looks like the beginning.",
      "That is where I come in.",
    ],
    glanceTitle: "At a glance",
    glance: [
      ["Focus", "New websites + complete rebuilds"],
      ["Best for", "Businesses + independent professionals"],
      ["Based in", "Costa Rica"],
      ["Languages", "English + Spanish"],
    ],
    introTitle: "I build websites from the ground up to match the business you have now.",
    intro: [
      "I’m Catalina, a web designer and developer based in Costa Rica.",
      "I help businesses turn what they do into a clear, considered digital experience — from structure and visual direction to development and launch.",
      "Rather than forcing every project into the same platform or template, I choose the design and technical approach based on what the project actually needs.",
    ],
  },
  build: {
    num: "03 / What I build",
    title: "A new website, built around where the business is now.",
    intro:
      "I work primarily on new websites and complete rebuilds — projects where we can rethink the experience properly instead of working around the limitations of an old setup.",
    new: {
      tag: "New website",
      lead: "For a business ready for its first serious online presence.",
      body: [
        "You may already have the clients, the work, and a clear direction, but no website that brings everything together properly.",
        "We start from the ground up and build the experience around the business you have today.",
      ],
    },
    rebuild: {
      tag: "Complete rebuild",
      lead: "For a business that has outgrown its current website.",
      body: [
        "The work improved. The positioning changed. The business became more established.",
        "Instead of patching an old site, we keep what is still valuable and rebuild the experience around where the business is going next.",
      ],
    },
    processTitle: "From direction to launch",
    process: [
      {
        n: "01",
        t: "Define",
        d: "We start with the business: what you offer, who needs to understand it, what has changed, and what the website should help people do.",
      },
      {
        n: "02",
        t: "Shape",
        d: "I turn that into the site structure, content hierarchy, and visual direction.",
      },
      {
        n: "03",
        t: "Build",
        d: "Once the direction is clear, I choose the technical approach that fits the project and build the responsive website.",
      },
      {
        n: "04",
        t: "Launch",
        d: "I test the important paths, prepare the production setup, connect the domain, and get the new website live.",
      },
    ],
  },
  work: {
    num: "04 / Selected work",
    title: "Different businesses. Different websites.",
    intro:
      "I do not start with a fixed template or platform. Each project is shaped around what the business needs to communicate, who it needs to reach, and what visitors should be able to do.",
    projects: [
      {
        n: "01",
        cat: "Medtech + AI",
        name: "Aster Intel",
        desc: "A digital presence for an AI-powered MedTech intelligence platform built for investors and corporate strategy teams.",
        body: "The website turns a complex product into a structured experience around its value, capabilities, use cases, security, and demo conversion.",
        roleLabel: "Role",
        role: "Website design + development",
        focusLabel: "Focus",
        focus: "Complex offer + B2B credibility",
        link: "Visit website",
      },
      {
        n: "02",
        cat: "Custom home building",
        name: "Kai Custom Homes",
        desc: "A full website for a custom home builder focused on high-end residential projects.",
        body: "The experience brings together the company’s positioning, completed homes, expertise, process, educational content, and lead generation into one consistent digital presence.",
        roleLabel: "Role",
        role: "Website design + development",
        focusLabel: "Focus",
        focus: "Premium positioning + lead generation",
        link: "Visit website",
      },
      {
        n: "03",
        cat: "Web services",
        name: "Baileyscode",
        desc: "A website for a Costa Rican web studio focused on businesses in tourism and hospitality.",
        body: "Built to position the service clearly, explain the offer, present completed work, and turn interested business owners into project inquiries.",
        roleLabel: "Role",
        role: "Brand direction + website design + development",
        focusLabel: "Focus",
        focus: "Service positioning + conversion",
        link: "Visit website",
      },
      {
        n: "04",
        cat: "Tourism",
        name: "Costa Rica Descents",
        desc: "A content-rich tourism website for an adventure company in La Fortuna.",
        body: "The site organizes a large catalog of rafting, adventure, food, and nature experiences into clearer categories and paths for visitors exploring what to book.",
        roleLabel: "Role",
        role: "Website development",
        focusLabel: "Focus",
        focus: "Content structure + tour discovery",
        link: "Visit website",
      },
      {
        n: "05",
        cat: "Hospitality",
        name: "Ester’s Place",
        desc: "A bilingual website for an independent guesthouse in Escazú.",
        body: "The experience brings together rooms, amenities, location, guest trust, local information, and booking paths to create a more complete online presence for the property.",
        roleLabel: "Role",
        role: "Website design + development",
        focusLabel: "Focus",
        focus: "Hospitality + direct inquiries",
        link: "Visit website",
      },
    ],
  },
  fit: {
    num: "05 / A good fit",
    title: "This works best when the business is ready for a real change.",
    intro: [
      "You do not need to know what platform to use or arrive with every page figured out.",
      "What matters is that you are ready to build something better instead of continuing to patch something that no longer fits.",
    ],
    items: [
      {
        n: "01",
        t: "You’re starting more seriously",
        d: "The work has become professional and you want the online presence to communicate that.",
        d2: "Maybe referrals, social media, or a simple page were enough before. Now you need something that represents the business properly.",
      },
      {
        n: "02",
        t: "You’ve outgrown the current site",
        d: "The business has changed, improved, or become more established — but the website still reflects an earlier stage.",
        d2: "You are not looking for another small update. You want the next version.",
      },
      {
        n: "03",
        t: "You want to start clean",
        d: "You would rather rethink the structure, design, and experience properly than continue working around an outdated setup.",
      },
      {
        n: "04",
        t: "You want design + development to work together",
        d: "You want the person shaping the experience to also understand how it will be built.",
        d2: "That keeps the design grounded, the development intentional, and the final result consistent from idea to launch.",
      },
    ],
  },
  contact: {
    num: "06 / Contact",
    title: "Ready for a website that matches where the business is now?",
    body: [
      "If the work has moved forward but the website has not, tell me what has changed and what you want the new version to do better.",
      "I’ll help you turn that into a clear direction and a website built around it.",
    ],
    cta: "Start a project",
    bestWay: "Best way to start",
    online: "Find me online",
    linkedin: "LinkedIn",
    github: "GitHub",
  },
  footer: {
    statement: "Websites built for where the business is going next.",
    backToTop: "Back to top",
    cv: "Download CV",
    tagline: "Web design + development / Costa Rica",
  },
};

export type Copy = typeof en;

export const es: Copy = {
  nav: [
    { href: "#positioning", label: "Posicionamiento" },
    { href: "#work", label: "Lo que construyo" },
    { href: "#projects", label: "Trabajo seleccionado" },
    { href: "#contact", label: "Contacto" },
  ],
  brand: "Catalina Cob",
  links: {
    email: "mailto:catalinacobap@gmail.com",
    linkedin: "#",
    github: "#",
    cv: "#",
  },
  hero: {
    label: "Diseño web + desarrollo / Costa Rica",
    titleA: "Su negocio ha crecido.",
    titleB: "su sitio web debería reflejarlo.",
    sub: "Sitios web a medida para negocios y profesionales independientes, listos para una presencia en línea que refleje la calidad de su trabajo hoy.",
    cta: "Iniciar un proyecto",
    strip: "Sitios web nuevos + rediseños completos",
    stripSuffix: "/ Costa Rica",
  },
  positioning: {
    num: "02 / Posicionamiento",
    title: "Cuando el trabajo mejora, el sitio web tiene que ponerse al día.",
    body: [
      "Quizás empezó con una plantilla, un sitio simple, una página de Instagram o algo que armó cuando el negocio todavía estaba tomando forma.",
      "Funcionó para esa etapa.",
      "Ahora el trabajo es más sólido, la oferta es más clara y el negocio se siente más establecido — pero el sitio web todavía se ve como al principio.",
      "Ahí es donde entro yo.",
    ],
    glanceTitle: "De un vistazo",
    glance: [
      ["Enfoque", "Sitios web nuevos + rediseños completos"],
      ["Ideal para", "Negocios + profesionales independientes"],
      ["Ubicada en", "Costa Rica"],
      ["Idiomas", "Inglés + Español"],
    ],
    introTitle: "Construyo sitios web desde cero para que estén a la altura del negocio que tiene hoy.",
    intro: [
      "Soy Catalina, diseñadora y desarrolladora web con base en Costa Rica.",
      "Ayudo a los negocios a convertir lo que hacen en una experiencia digital clara y pensada — desde la estructura y la dirección visual hasta el desarrollo y el lanzamiento.",
      "En lugar de forzar cada proyecto en la misma plataforma o plantilla, elijo el enfoque de diseño y técnico según lo que el proyecto realmente necesita.",
    ],
  },
  build: {
    num: "03 / Lo que construyo",
    title: "Un sitio web nuevo, construido alrededor de donde está el negocio ahora.",
    intro:
      "Trabajo principalmente en sitios web nuevos y rediseños completos — proyectos donde podemos repensar la experiencia de verdad, en lugar de trabajar alrededor de las limitaciones de una instalación vieja.",
    new: {
      tag: "Sitio web nuevo",
      lead: "Para un negocio listo para su primera presencia en línea seria.",
      body: [
        "Quizás ya tiene los clientes, el trabajo y una dirección clara, pero ningún sitio web que lo reúna todo como corresponde.",
        "Empezamos desde cero y construimos la experiencia alrededor del negocio que tiene hoy.",
      ],
    },
    rebuild: {
      tag: "Rediseño completo",
      lead: "Para un negocio que ha superado su sitio web actual.",
      body: [
        "El trabajo mejoró. El posicionamiento cambió. El negocio se hizo más establecido.",
        "En lugar de remendar un sitio viejo, conservamos lo que todavía es valioso y reconstruimos la experiencia alrededor de hacia dónde va el negocio.",
      ],
    },
    processTitle: "De la dirección al lanzamiento",
    process: [
      {
        n: "01",
        t: "Definir",
        d: "Empezamos con el negocio: qué ofrece, quién necesita entenderlo, qué ha cambiado y qué debería ayudar a hacer el sitio web.",
      },
      {
        n: "02",
        t: "Moldear",
        d: "Convierto eso en la estructura del sitio, la jerarquía de contenido y la dirección visual.",
      },
      {
        n: "03",
        t: "Construir",
        d: "Una vez clara la dirección, elijo el enfoque técnico que encaja con el proyecto y construyo el sitio web responsivo.",
      },
      {
        n: "04",
        t: "Lanzar",
        d: "Pruebo los caminos importantes, preparo la configuración de producción, conecto el dominio y pongo el sitio web nuevo en línea.",
      },
    ],
  },
  work: {
    num: "04 / Trabajo seleccionado",
    title: "Negocios diferentes. Sitios web diferentes.",
    intro:
      "No empiezo con una plantilla o plataforma fija. Cada proyecto se forma alrededor de lo que el negocio necesita comunicar, a quién necesita llegar y qué deberían poder hacer los visitantes.",
    projects: [
      {
        n: "01",
        cat: "Medtech + IA",
        name: "Aster Intel",
        desc: "Una presencia digital para una plataforma de inteligencia MedTech impulsada por IA, construida para inversionistas y equipos de estrategia corporativa.",
        body: "El sitio convierte un producto complejo en una experiencia estructurada alrededor de su valor, capacidades, casos de uso, seguridad y conversión de demo.",
        roleLabel: "Rol",
        role: "Diseño + desarrollo web",
        focusLabel: "Enfoque",
        focus: "Oferta compleja + credibilidad B2B",
        link: "Visitar el sitio",
      },
      {
        n: "02",
        cat: "Construcción de casas a medida",
        name: "Kai Custom Homes",
        desc: "Un sitio web completo para un constructor de casas a medida enfocado en proyectos residenciales de alta gama.",
        body: "La experiencia reúne el posicionamiento de la empresa, las casas terminadas, la experiencia, el proceso, el contenido educativo y la generación de clientes potenciales en una sola presencia digital coherente.",
        roleLabel: "Rol",
        role: "Diseño + desarrollo web",
        focusLabel: "Enfoque",
        focus: "Posicionamiento premium + generación de leads",
        link: "Visitar el sitio",
      },
      {
        n: "03",
        cat: "Servicios web",
        name: "Baileyscode",
        desc: "Un sitio web para un estudio web costarricense enfocado en negocios de turismo y hospitalidad.",
        body: "Construido para posicionar el servicio con claridad, explicar la oferta, presentar el trabajo realizado y convertir a dueños de negocios interesados en consultas de proyecto.",
        roleLabel: "Rol",
        role: "Dirección de marca + diseño + desarrollo web",
        focusLabel: "Enfoque",
        focus: "Posicionamiento de servicio + conversión",
        link: "Visitar el sitio",
      },
      {
        n: "04",
        cat: "Turismo",
        name: "Costa Rica Descents",
        desc: "Un sitio web de turismo rico en contenido para una empresa de aventura en La Fortuna.",
        body: "El sitio organiza un catálogo grande de experiencias de rafting, aventura, gastronomía y naturaleza en categorías y caminos más claros para los visitantes que exploran qué reservar.",
        roleLabel: "Rol",
        role: "Desarrollo web",
        focusLabel: "Enfoque",
        focus: "Estructura de contenido + descubrimiento de tours",
        link: "Visitar el sitio",
      },
      {
        n: "05",
        cat: "Hospitalidad",
        name: "Ester’s Place",
        desc: "Un sitio web bilingüe para una guesthouse independiente en Escazú.",
        body: "La experiencia reúne habitaciones, servicios, ubicación, confianza de huéspedes, información local y rutas de reserva para crear una presencia en línea más completa para la propiedad.",
        roleLabel: "Rol",
        role: "Diseño + desarrollo web",
        focusLabel: "Enfoque",
        focus: "Hospitalidad + consultas directas",
        link: "Visitar el sitio",
      },
    ],
  },
  fit: {
    num: "05 / Un buen encaje",
    title: "Esto funciona mejor cuando el negocio está listo para un cambio real.",
    intro: [
      "No necesita saber qué plataforma usar ni llegar con cada página resuelta.",
      "Lo que importa es que esté listo para construir algo mejor en lugar de seguir remendando algo que ya no encaja.",
    ],
    items: [
      {
        n: "01",
        t: "Está empezando más en serio",
        d: "El trabajo se volvió profesional y quiere que la presencia en línea lo comunique.",
        d2: "Quizás antes bastaban las referencias, las redes sociales o una página simple. Ahora necesita algo que represente el negocio como corresponde.",
      },
      {
        n: "02",
        t: "Superó el sitio actual",
        d: "El negocio cambió, mejoró o se hizo más establecido — pero el sitio web todavía refleja una etapa anterior.",
        d2: "No está buscando otra actualización pequeña. Quiere la siguiente versión.",
      },
      {
        n: "03",
        t: "Quiere empezar en limpio",
        d: "Prefiere repensar la estructura, el diseño y la experiencia como corresponde, en lugar de seguir trabajando alrededor de una configuración desactualizada.",
      },
      {
        n: "04",
        t: "Quiere que diseño + desarrollo trabajen juntos",
        d: "Quiere que la persona que da forma a la experiencia también entienda cómo se va a construir.",
        d2: "Eso mantiene el diseño con los pies en la tierra, el desarrollo intencional y el resultado final coherente desde la idea hasta el lanzamiento.",
      },
    ],
  },
  contact: {
    num: "06 / Contacto",
    title: "¿Listo para un sitio web que esté a la altura de donde está su negocio?",
    body: [
      "Si el trabajo avanzó pero el sitio web no, cuénteme qué ha cambiado y qué quiere que la nueva versión haga mejor.",
      "Le ayudaré a convertir eso en una dirección clara y en un sitio web construido alrededor de ella.",
    ],
    cta: "Iniciar un proyecto",
    bestWay: "La mejor forma de empezar",
    online: "Encuéntreme en línea",
    linkedin: "LinkedIn",
    github: "GitHub",
  },
  footer: {
    statement: "Sitios web construidos para donde va el negocio.",
    backToTop: "Volver arriba",
    cv: "Descargar CV",
    tagline: "Diseño + desarrollo web / Costa Rica",
  },
};

export const copy: Record<Lang, Copy> = { en, es };
