export type Lang = "en" | "es";

export const en = {
  nav: [
    { href: "#positioning", label: "Positioning" },
    { href: "#at-a-glance", label: "At a glance" },
    { href: "#about", label: "About" },
    { href: "#what-i-build", label: "What I build" },
    { href: "#process", label: "Process" },
    { href: "#selected-work", label: "Selected work" },
    { href: "#a-good-fit", label: "A good fit" },
    { href: "#investment", label: "Investment" },
    { href: "#contact", label: "Contact" },
  ],
  brand: "Catalina Cobap",
  links: {
    email: "mailto:catalinacobap@gmail.com",
    linkedin: "#",
    github: "#",
    cv: "https://docs.google.com/document/d/1ZT_LXHi_dx4Z-HlCwThasDIjoyxdMLnrpJmPymGnG54/edit?usp=sharing",
  },
  hero: {
    label: "WEB DESIGN + DEVELOPMENT / COSTA RICA",
    titleA: "Not every web project needs the same thing.",
    titleB: "WEBSITES AND MVPs, BUILT FOR WHAT THEY NEED TO DO.",
    sub: "Design and development from scratch — from a new web presence to the first functional version of a product.",
    cta: "START A PROJECT",
    strip: "WEBSITES FROM SCRATCH · WEBAPP MVPs · DESIGN + DEVELOPMENT ·",
    stripSuffix: "/ COSTA RICA",
  },
  positioning: {
    num: "POSITIONING",
    title: "First, what it needs to do. Then, how to build it.",
    body: "Every project starts by understanding what it needs to communicate, enable, or solve. Structure, design, and technology come after that.",
    glanceTitle: "AT A GLANCE",
    glance: [
      ["FOCUS", "Websites + webapp MVPs"],
      ["WEBSITES", "$1,000–$1,500 USD"],
      ["MVPS", "From $2,000 USD"],
      ["BASED IN", "Costa Rica"],
      ["LANGUAGES", "Spanish + English"],
    ],
  },
  about: {
    num: "ABOUT",
    statement:
      "I design and develop every project from scratch — around what it needs to do, not around a solution decided in advance.",
    name: "Catalina",
    monogram: "C.",
    note: "Web designer + developer, Costa Rica.",
  },
  build: {
    num: "WHAT I BUILD",
    title: "Two starting points.",
    intro: "One needs to communicate. The other needs people to be able to do something.",
    new: {
      tag: "WEBSITES FROM SCRATCH",
      lead: "“I need a web presence.”",
      body: "For businesses and independent professionals that need a new website — whether it is their first serious site or a new one built to completely replace the one they have today.",
      secondaryBody: "I design and develop the new version from scratch, around the business, the content, and what the website needs to accomplish.",
      price: "$1,000–$1,500 USD",
      cta: "VIEW WEBSITES",
      link: "/sitios-web",
    },
    rebuild: {
      tag: "WEBAPP MVP",
      lead: "“I need people to be able to do something inside the product.”",
      body: "For ideas that need to become functional: users, data, flows, dashboards, integrations, or custom product logic.",
      secondaryBody: "We define what needs to exist in the first version, and I build an MVP ready to be put into use.",
      price: "FROM $2,000 USD",
      cta: "VIEW WEBAPP MVPs",
      link: "/mvp-webapp",
    },
    processTitle: "FROM DIRECTION TO LAUNCH",
    process: [
      { n: "01", t: "DEFINE", d: "What it needs to do, who needs it, and what actually matters." },
      { n: "02", t: "SHAPE", d: "Structure, hierarchy, flows, and visual direction." },
      { n: "03", t: "BUILD", d: "Design and development together, using the technology that makes sense for the project." },
      { n: "04", t: "LAUNCH", d: "Testing, production setup, domain, and going live." },
    ],
  },
  work: {
    num: "SELECTED WORK",
    title: "Different projects. Different solutions.",
    intro: "Each project takes shape around what it needs to communicate, organize, or enable.",
    projects: [
      {
        n: "01",
        cat: "MEDTECH + AI",
        name: "Aster Intel",
        desc: "An intelligence platform presented clearly for investors.",
        link: "VISIT SITE",
        url: "https://asterintel.ai",
      },
      {
        n: "02",
        cat: "CUSTOM HOME CONSTRUCTION",
        name: "Kai Custom Homes",
        desc: "A digital presence that matches the level of a premium home builder.",
        link: "VISIT SITE",
        url: "https://kai-customhomes.com",
      },
      {
        n: "03",
        cat: "WEB SERVICES",
        name: "Baileyscode",
        desc: "A Costa Rican web studio focused on tourism and hospitality.",
        link: "VISIT SITE",
        url: "https://www.baileyscode.com",
      },
      {
        n: "04",
        cat: "TOURISM",
        name: "Costa Rica Descents",
        desc: "A large tour catalog, organized for easy discovery.",
        link: "VISIT SITE",
        url: "https://costaricadescents.com",
      },
      {
        n: "05",
        cat: "HOSPITALITY",
        name: "Ester’s Place",
        desc: "A complete bilingual web presence for a Costa Rican accommodation business.",
        link: "VISIT SITE",
        url: "https://estersplace.com",
      },
    ],
  },
  fit: {
    num: "A GOOD FIT",
    title: "It works best when you want to build something properly.",
    items: [
      { t: "YOU NEED SOMETHING BUILT FOR YOUR CASE", d: "Not a generic solution forced to fit, but a structure designed around the project." },
      { t: "YOU WANT TO START WITH A CLEAN FOUNDATION", d: "A new project, or a new version, without carrying technical decisions that no longer make sense." },
      { t: "YOU UNDERSTAND THE PROBLEM", d: "You know what needs to improve, launch, or start working, even if you do not yet know exactly how it should be built." },
      { t: "YOU WANT DESIGN + DEVELOPMENT TOGETHER", d: "One person thinks through the experience, designs it, and builds it from beginning to end." },
    ],
  },
  investment: {
    num: "INVESTMENT",
    title: "Clear scope. Clear price.",
    websites: {
      title: "WEBSITES FROM SCRATCH",
      price: "$1,000–$1,500 USD",
      body: "For new websites and new websites built from scratch to replace an existing one.",
      secondaryBody: "Pricing depends mainly on scope, number of pages, content, and required integrations.",
      cta: "VIEW WEBSITES",
      link: "/sitios-web",
    },
    mvps: {
      title: "WEBAPP MVPs",
      price: "FROM $2,000 USD",
      body: "For first functional versions of web products.",
      secondaryBody: "Pricing depends on what the MVP needs to do: users, data, roles, dashboards, integrations, logic, or other product flows.",
      cta: "VIEW MVPs",
      link: "/mvp-webapp",
    },
    footnote: "After I understand the project, I define the scope and price before work begins.",
  },
  contact: {
    num: "CONTACT",
    title: "Have something you need to build?",
    body: "Tell me what you want to launch, replace, or put into operation.",
    cta: "START A PROJECT",
    bestWay: "BEST WAY TO START",
    online: "FIND ME ONLINE",
    linkedin: "LINKEDIN",
    github: "GITHUB",
  },
  footer: {
    backToTop: "↑ BACK TO TOP",
    cv: "DOWNLOAD CV",
    tagline: "WEB DESIGN + DEVELOPMENT / COSTA RICA",
    copyright: "© 2026 CATALINA COBAP — WEB DESIGN + DEVELOPMENT / COSTA RICA",
  },
};
export const es = {
  nav: [
    { href: "#posicionamiento", label: "Posicionamiento" },
    { href: "#de-un-vistazo", label: "De un vistazo" },
    { href: "#sobre-mi", label: "Sobre mí" },
    { href: "#lo-que-construyo", label: "Lo que construyo" },
    { href: "#proceso", label: "Proceso" },
    { href: "#trabajo-seleccionado", label: "Trabajo seleccionado" },
    { href: "#un-buen-encaje", label: "Un buen encaje" },
    { href: "#inversion", label: "Inversión" },
    { href: "#contacto", label: "Contacto" },
  ],
  brand: "Catalina Cobap",
  links: {
    email: "mailto:catalinacobap@gmail.com",
    linkedin: "#",
    github: "#",
    cv: "https://docs.google.com/document/d/1ZT_LXHi_dx4Z-HlCwThasDIjoyxdMLnrpJmPymGnG54/edit?usp=sharing",
  },
  hero: {
    label: "DISEÑO WEB + DESARROLLO / COSTA RICA",
    titleA: "No todos los proyectos web necesitan lo mismo.",
    titleB: "SITIOS WEB Y MVPs, CONSTRUIDOS PARA LO QUE TIENEN QUE HACER.",
    sub: "Diseño y desarrollo desde cero: desde una nueva presencia web hasta la primera versión funcional de un producto.",
    cta: "INICIAR UN PROYECTO",
    strip: "SITIOS WEB DESDE CERO · MVPs DE WEBAPPS · DISEÑO + DESARROLLO ·",
    stripSuffix: "/ COSTA RICA",
  },
  positioning: {
    num: "POSICIONAMIENTO",
    title: "Primero lo que tiene que hacer. Después cómo construirlo.",
    body: "Cada proyecto empieza por entender qué necesita comunicar, permitir o resolver. La estructura, el diseño y la tecnología vienen después.",
    glanceTitle: "DE UN VISTAZO",
    glance: [
      ["ENFOQUE", "Sitios web + MVPs de webapps"],
      ["SITIOS WEB", "$1,000–$1,500 USD"],
      ["MVPS", "Desde $2,000 USD"],
      ["UBICADA EN", "Costa Rica"],
      ["IDIOMAS", "Español + Inglés"],
    ],
  },
  about: {
    num: "SOBRE MÍ",
    statement:
      "Diseño y desarrollo cada proyecto desde cero — alrededor de lo que necesita hacer, no de una solución decidida de antemano.",
    name: "Catalina",
    monogram: "C.",
    note: "Diseñadora + desarrolladora web, Costa Rica.",
  },
  build: {
    num: "LO QUE CONSTRUYO",
    title: "Dos puntos de partida.",
    intro: "Uno necesita comunicar. El otro necesita que las personas puedan hacer algo.",
    new: {
      tag: "SITIOS WEB DESDE CERO",
      lead: "“Necesito una presencia web.”",
      body: "Para negocios y profesionales que necesitan un sitio nuevo — ya sea el primero o uno nuevo para reemplazar el que tienen hoy.",
      secondaryBody: "Diseño y desarrollo la nueva versión desde cero, alrededor del negocio, el contenido y lo que el sitio necesita conseguir.",
      price: "$1,000–$1,500 USD",
      cta: "VER SITIOS WEB",
      link: "/sitios-web",
    },
    rebuild: {
      tag: "MVP DE WEBAPP",
      lead: "“Necesito que las personas puedan hacer algo dentro del producto.”",
      body: "Para ideas que necesitan convertirse en algo funcional: usuarios, datos, flujos, dashboards, integraciones o lógica propia.",
      secondaryBody: "Definimos qué necesita existir en la primera versión y construyo un MVP listo para poner en uso.",
      price: "DESDE $2,000 USD",
      cta: "VER MVPs DE WEBAPPS",
      link: "/mvp-webapp",
    },
    processTitle: "DE LA DIRECCIÓN AL LANZAMIENTO",
    process: [
      { n: "01", t: "DEFINIR", d: "Qué necesita hacer, quién lo necesita y qué importa de verdad." },
      { n: "02", t: "MOLDEAR", d: "Estructura, jerarquía, flujos y dirección visual." },
      { n: "03", t: "CONSTRUIR", d: "Diseño y desarrollo juntos, con la tecnología adecuada para el proyecto." },
      { n: "04", t: "LANZAR", d: "Pruebas, producción, dominio y puesta en línea." },
    ],
  },
  work: {
    num: "TRABAJO SELECCIONADO",
    title: "Proyectos diferentes. Soluciones diferentes.",
    intro: "Cada proyecto toma forma alrededor de lo que necesita comunicar, organizar o permitir.",
    projects: [
      {
        n: "01",
        cat: "MEDTECH + IA",
        name: "Aster Intel",
        desc: "Una plataforma de inteligencia presentada con claridad para inversionistas.",
        link: "VISITAR SITIO",
        url: "https://asterintel.ai",
      },
      {
        n: "02",
        cat: "CONSTRUCCIÓN DE CASAS A MEDIDA",
        name: "Kai Custom Homes",
        desc: "Una presencia digital a la altura de un constructor premium.",
        link: "VISITAR SITIO",
        url: "https://kai-customhomes.com",
      },
      {
        n: "03",
        cat: "SERVICIOS WEB",
        name: "Baileyscode",
        desc: "Un estudio web costarricense enfocado en turismo y hospitalidad.",
        link: "VISITAR SITIO",
        url: "https://www.baileyscode.com",
      },
      {
        n: "04",
        cat: "TURISMO",
        name: "Costa Rica Descents",
        desc: "Un catálogo amplio de tours organizado para explorar con facilidad.",
        link: "VISITAR SITIO",
        url: "https://costaricadescents.com",
      },
      {
        n: "05",
        cat: "HOSPITALIDAD",
        name: "Ester’s Place",
        desc: "Una presencia bilingüe completa para un hospedaje en Costa Rica.",
        link: "VISITAR SITIO",
        url: "https://estersplace.com",
      },
    ],
  },
  fit: {
    num: "UN BUEN ENCAJE",
    title: "Funciona mejor cuando quiere construir algo bien hecho.",
    items: [
      { t: "NECESITA ALGO HECHO PARA SU CASO", d: "No una solución genérica adaptada a la fuerza, sino una estructura pensada alrededor del proyecto." },
      { t: "QUIERE EMPEZAR CON UNA BASE LIMPIA", d: "Un proyecto nuevo, o una nueva versión, sin cargar con decisiones técnicas que ya no tienen sentido." },
      { t: "TIENE CLARO EL PROBLEMA", d: "Sabe qué necesita mejorar, lanzar o poner en funcionamiento, aunque todavía no sepa exactamente cómo construirlo." },
      { t: "QUIERE DISEÑO + DESARROLLO JUNTOS", d: "Una misma persona piensa la experiencia, la diseña y la construye de principio a fin." },
    ],
  },
  investment: {
    num: "INVERSIÓN",
    title: "Alcance claro. Precio claro.",
    websites: {
      title: "SITIOS WEB DESDE CERO",
      price: "$1,000–$1,500 USD",
      body: "Para sitios nuevos y sitios construidos desde cero para reemplazar uno existente.",
      secondaryBody: "El precio depende principalmente del alcance, número de páginas, contenido e integraciones necesarias.",
      cta: "VER SITIOS WEB",
      link: "/sitios-web",
    },
    mvps: {
      title: "MVPs DE WEBAPPS",
      price: "DESDE $2,000 USD",
      body: "Para primeras versiones funcionales de productos web.",
      secondaryBody: "El precio depende de lo que necesite hacer el MVP: usuarios, datos, roles, dashboards, integraciones, lógica u otros flujos.",
      cta: "VER MVPs",
      link: "/mvp-webapp",
    },
    footnote: "Después de conocer el proyecto, defino el alcance y el precio antes de empezar.",
  },
  contact: {
    num: "CONTACTO",
    title: "¿Tiene algo que necesita construir?",
    body: "Cuénteme qué quiere lanzar, reemplazar o poner en funcionamiento.",
    cta: "INICIAR UN PROYECTO",
    bestWay: "MEJOR FORMA DE EMPEZAR",
    online: "ENCUÉNTREME EN LÍNEA",
    linkedin: "LINKEDIN",
    github: "GITHUB",
  },
  footer: {
    backToTop: "↑ VOLVER ARRIBA",
    cv: "DESCARGAR CV",
    tagline: "DISEÑO WEB + DESARROLLO / COSTA RICA",
    copyright: "© 2026 CATALINA COBAP — DISEÑO WEB + DESARROLLO / COSTA RICA",
  },
};
export type Copy = typeof en;

export const copy: Record<Lang, Copy> = { en, es };
